### ISSUE TITLE
Please refer to igraph instead of python-igraph

### ISSUE THREAD

**Issue by szhorvat** [Otter-Taskification/pyotter#3]
Please refer to `igraph` instead of `python-igraph` in the following two locations:

https://github.com/search?q=repo%3AOtter-Taskification%2Fpyotter%20python-igraph&type=code

Please see https://github.com/igraph/python-igraph/issues/699 for an explanation.

I did not submit a PR as I saw that you pinned igraph to 0.9.1, which is in fact not available under the new name.  Consider removing the pin or opening an issue if there's a problem with newer versions.

**Comment by adamtuft** [comment]
Thanks for your comment! This is fixed with a032e30 and [6188f52](https://github.com/Otter-Taskification/pyotter/commit/6188f520f0ef34ad7a1c9dc23527f9642d8c46c2).
